---
title: "Type I errors, model rejection, & HiSSE vs. FiSSE"
author: "Jeremy M. Beaulieu & Brian C O'Meara"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: rmarkdown::html_vignette
vignette: >
   %\VignetteEngine{knitr::rmarkdown}
   %\VignetteIndexEntry{Running hisse}
   \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

An very important concern was recently raised by Rabosky and Goldberg (2015). They demonstrated, rather convincingly, that if a tree evolved under a heterogeneous branching process that is completely independent from the evolution of the focal character, SSE models (State Speciation and Extinction; Maddison et al 2007) will almost always return high support for a model of trait-dependent diversification. From an interpretational stand point, this is troubling. However, it is important to bear in mind that SSE models are not typical trait evolution models, like those in, say Pagel (1994) or Hansen (1997), where the probability of the observed states is maximized at the tips, given the tree and model -- the tree certainly affects the likelihood of the tip data, but that is the only way it enters the calculation. A trait-based diversification model, on the other hand, jointly maximizes the probability of the observed states at the tips *and* the observed tree, given the model. So, if a tree violates a single regime birth–death model due to mass extinction events, trait-dependent speciation or extinction, maximum carrying capacity, climate change affecting speciation rates, or whatever, then even if the tip data are perfectly consistent with a simple transition model, the tip data plus the tree are not. More simply put: Yes, in such cases BiSSE is very wrong in assigning rate differences to a neutral trait, but a simple equal rates diversification model is not correct either. This leaves practitioners in quite the bind, because the "right" model isn't something that can be tested in BiSSE.

Neverthless, these results have created a percieved "crisis" among empiricists, perhaps rightly so, with respect to SSE models. It is our view, however, this crisis is a bit overstated. First, rejecting the null model does not imply that the alternative model is the true model. It simply means that the alternative model fits better. Second, we very much disagree that this represents Type I error, as was suggested by Rabosky and Goldberg (2015). It is simply rejecting model A for model B when model C is true. There’s a mnemonic for remembering Type I versus Type II error that was recently making the rounds on social media -- the story of the boy that cried wolf. When he first cried wolf, but there was no wolf, he was making a Type I error (falsely rejecting the null of a wolf-free meadow). When the townspeople later ignored him when there was actually a wolf, they were making a Type II error. If the sheep were instead perishing in a snowstorm, and the only options for the boy are to yell "no wolf!" or "wolf!" it is not clear what the best behavior is: "no wolf" implies no change in sheep mortality rates from when they happily gambol in a sunny meadow, even though they have begun to perish, while "wolf" communicates the mortality increase but has the wrong mechanism. It is the same here when looking at a tree coming from an unknown but complex empirical branching model and trying to compare a constant rate model ("no wolf") with a trait-dependent, age-dependent, or density-dependent model ("wolf", "bear", "piranha", etc.).  

In any event, it is clear that ever since SSE models became standard practice, we've relied a bit too heavily on rather trivial "null" models (i.e., equal rates diversification) to compare against models of trait dependent diversification. A fairer comparison would need to involve some sort of "null" model that contains the same degree of complexity in terms of numbers of parameters for diversification, but is also independent of the evolution of the focal character, to allow for comparisons among any complex, trait-dependent models of interest. 

In Beaulieu and O'Meara (2016), we proposed two such models. These character-independent (CID) models explicitly assume that the evolution of a binary character is independent of the diversification process without forcing the diversification process to be constant across the entire tree. The first model, which we refer to as "CID-2", contains four diversification process parameters that account for trait-dependent diversification solely on the two states of an unobserved, hidden trait. In this way, CID-2 contains the same amount of complexity in terms of diversification as a BiSSE model. The second model, which we refer to as "CID-4" contains the same number of diversification parameters as in the general HiSSE model that are linked across four hidden states. But, more on these models in a moment.

In the our HiSSE paper, we conducted a series of simulations where a species tree evolved under a complex, and sometimes unknown, diversification process, but with the focal trait evolving under a simple model independent of diversification parameters. In all cases, when the generating model was more consistent with a character-independent diversification model, we found our CID models substantially reduced the evidence favoring the trait-dependent models (i.e., BiSSE and HiSSE). In fact, we even tested what we referred to as our "worst-case" scenario, which involved first simulating trees where speciation rate evolved in a heterogeneous manner, and then simulating a neutral binary character onto them. Without our CID models being included in the model set under evaluation, the BiSSE model had substantial support nearly 80% of the time. However, when we added just the CID-2 model, only 1% of those same data sets showed substantial support for BiSSE. When we tested the full set, which included both HiSSE and CID-4, in addition to BiSSE and CID-2, 16% of the time either BiSSE or HiSSE model had substantial support. Comparing the parameter estimates from those data sets indicated that the differences in the parameter estimates among the different observed states were minimal. Thus, even if a trait-dependent model were to be chosen, the parameter estimates would suggest any rates differences are likely biologically insignificant.

## HiSSE vs. FiSSE

Recently, Rabosky and Goldberg (2017) proposed a simple nonparametric test for determining the effect of a binary character on rates of diversification. The performance of FiSSE is encouraging from the standpoint of model rejection -- that is, under a range of very difficult, and often extreme scenarios, FiSSE can differentiate between scenarios of trait-dependent and trait-independent diversification fairly well (see their Fig. 6). For good measure, they also compared the performance of HiSSE under these same scenarios, and found that while the inclusion of our CID-2 model reduced the overall "false positive" rate of BiSSE, the use of BiSSE + CID-2 + HiSSE resulted in nine of 34 trait-independent diversification scenarios (referred to as SDD in Rabosky and Goldberg 2017) having "false-positive" rates in excess of 25%. 

While we do not dispute the results as they are presented in Rabosky and Goldberg (2017), we do feel that the HiSSE model comparisons were not conducted quite in the manner in which we intended. As stated above, the CID-2 model was derived to contain the same amount of complexity in terms of diversification as a BiSSE model. That is, our CID-2 has two speciation rates ($\lambda_{0A} = \lambda_{1A}$, $\lambda_{0B} = \lambda_{1B}$) and two extinction rates ($\mu_{0A} = \mu_{1A}$, $\mu_{0B} = \mu_{1B}$) same as BiSSE ($\lambda_0$, $\lambda_1$, $\mu_0$, $\mu_1$). However, when HiSSE is included, it is much more complex than either BiSSE or CID-2. So, again, if the complexity of the process that generated the tree exceeds that of the CID-2 model in any of the non-SDD scenarios, then we expect the more complex HiSSE model to fit better for precisely same reasons as described above -- the model in the set that best matches the complexity of the scenario is in fact a trait-dependent model of diversification. This is precisely why we also derived the CID-4 model, which equals the same complexity as HiSSE. Like HiSSE, which has four speciation rates ($\lambda_{0A}$, $\lambda_{1A}$, $\lambda_{0B}$, $\lambda_{1B}$) and extinction rates ($\mu_{0A}$, $\mu_{1A}$, $\mu_{0B}$, $\mu_{1B}$), the CID-4 also has four speciation rates ($\lambda_{0A} = \lambda_{1A}$, $\lambda_{0B} = \lambda_{1B}$, $\lambda_{0C} = \lambda_{1C}$, $\lambda_{0D} = \lambda_{1D}$) and four extinction rates ($\mu_{0A} = \mu_{1A}$, $\mu_{0B} = \mu_{1B}$, $\mu_{0C} = \mu_{1C}$, $\mu_{0D} = \mu_{1D}$). In other words, the two models are equally complex with respect to diversification, but have entirely different interpretations with respect whether or not there is trait-dependent diversification. 

## Reanalysis of Rabosky and Goldberg (2017) with CID-4 in the set

It is important to emphasize that we are not suggesting any nefarious malfeasance on the part of the Rabosky and Goldberg (2017). In fact, despite the seemingly poor performance of HiSSE under many of their scenarios, they still recommend that FiSSE simply complement formal process-based models of trait-dependent diversification such as ours. But, we have also noticed that many users seem either completely unaware of our CID models, or are at least reluctant to include them in the set of models they are evaluating. So, the purpose of this section is to simply demonstrate how important it is that when HiSSE models are included in a set of models that the CID-4 is also included. This is so that if the goal of the test is to reject null models, there are null models with at least a fighting chance. 

First, a note about the trait-independent scenarios (i.e., no SDD) presented in Rabosky and Goldberg (2017). These represent some of the most extreme cases we've encountered when testing the performance of HiSSE. Out of the 34 trait-independent scenarios, 27 were trees either simulated (19 of the 27 scenarios) to have a total height of 1, or were empirical trees (8 of the 27) that were rescaled so that their total height is 1. Thus, the parameter estimates were almost always rather extreme (e.g., speciation rates >50) and in several cases posed rather serious problems for our optimization routine. This is, of course, a criticism of us, not of Rabosky and Goldberg (2017). To overcome these issues, starting with version 1.8.3 the optimization defaults to a bounded subplex routine where we set the upper bounds to be reasonable with respect what we think is biologically realistic. For example, the upper bound on turnover (i.e., $\lambda_i + \mu_i$) is set to 10000, which assumes, on average, one event per 100 years. For extinction fraction, (i.e., $\mu_i / \lambda_i$), the upper limit is set to 3, which, in our view, far exceeds the extinction fraction of any observable extant clade. We also now include a new setting, ode.eps, that sets the tolerance for the integration at the end of a branch. Essentially if the sum of the probability of $D_i$ is less than this tolerance, then it assumes the results are unstable and discards them. For the present purposes, however, the ode.eps was set to zero. 

Points to make:
1) We actually did worse than Rabosky and Goldberg said we did when you don't include CID-4 under the bounded search.
2) Including CID-4 always reduces the "false positive" rate -- in one case go from 80% to 8%. 
3) Parsimony scores for the empirical non-SDD data sets predicts the false-positive rate -- why? I don't know yet. Simulated trees, across the board, show no pattern between parsimony scores and false positive rates 
4) #37, 42, 43 all the same data sets. #37 seems really weird because from the description says that neutral character, but one clade chosen at random to be fixed to one state. Not clear if truly non-SDD, so at best may actually represent a Darwin scenario sensu Maddison and FitzJohn 2014. 
5) Overall, we do really well. Doing FiSSE would be added evidence, again, if model rejection is the goal.

## What do we recommend when comparing a large set of models?


